### PR TITLE
Fix foreground color reset to default after each WriteInColor call

### PR DESCRIPTION
**Pull request by k0rsh**
As per issue #26 this fragment of code was not usable:
```
Colorful.Console.ForegroundColor = color;
Colorful.Console.WriteLine($"Foregound Console Color : \"{Colorful.Console.ForegroundColor.ToString()}\"");
color = System.Drawing.Color.DeepSkyBlue;
Colorful.Console.WriteLine($"Console Color : \"{color.ToString()}\"", color);
Colorful.Console.WriteLine($"Foregound Console Color : \"{Colorful.Console.ForegroundColor.ToString()}\"");
```

The issue was in WriteInColor group of methods (ColorfulConsoleBack.cs), which called System.Console.ResetColor() after each method call.
I've added plain System.Console.ForegroundColor save to a local variable and reverting it back instead of calling ResetColor().

### CODE REVIEW

**Comment by tomakita** [comment]
Thanks for the bug fix!  The changes in ColorfulConsoleBack.cs look great.  I've noticed that this PR also replaces project.json and .xproj with .csproj -- was this intentional?

**Comment by k0rsh** [comment]
Hi! It wasn't intentional, VS 2017 Community edition forces these changes with no other chance to load the solution other than migration from xproj to csproj. Sorry.

**Comment by tomakita** [comment]
Understood, I figured it might be VS 2017.  Would it be possible to submit a PR with just the changes in ColorfulConsoleBack.cs?  I can simply make these changes in my branch and then merge to master, but I'd like for you to get credit for this fix if possible.  Sorry to make you jump through hoops to get this merged!

**Comment by k0rsh** [comment]
Never mind, code changes have no dependencies of VS2017 in particular. Surely you can merge just the class code without project files.

**Comment by tomakita** [comment]
Unfortunately, Git doesn't give us that much granularity when merging -- we can only merge by commit.  BUT, I ended up figuring out how to do this via the command line: I manually made the changes in a local copy of the repo, and then was able to commit and push them in your name:

https://github.com/tomakita/Colorful.Console/commit/b00372e31ba754ce49423e23119c9cc89c77060b

You are officially listed as a contributor now.  (And the crowd goes wild!!)

Thanks again!

**Pull request closed without merging**
