### PR TITLE
Ascii Art using Figlet Fonts

### PR DESCRIPTION
**Pull request by RehanSaeed**
I added Ascii art support using Figlet fonts. Take a look at the example project for usage details.

```
Console.WriteAscii("Hello World");
Console.WriteAscii("Hello World", new FigletFont(File.Open(flfFontFilePath)));
```

There are other overloads to add colour which work well. I also took the opportunity to update your .gitignores file from the one [here](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) and deleted obj and bin folders which are bad for git.

The only thing stopping this project from targetting .NET 4 is these three properties:

```
        public static bool IsErrorRedirected
        {
            get { return System.Console.IsErrorRedirected; }
        }

        public static bool IsInputRedirected
        {
            get { return System.Console.IsInputRedirected; }
        }

        public static bool IsOutputRedirected
        {
            get { return System.Console.IsOutputRedirected; }
        }
```

If you made the switch to .xproj you can easily add .NET 4.0 support by adding:

```
#if !NET4
// The above code here
#endif
```

This would give you a wider audience with little effort. Also consider adding a NuGet icon, with 'Colourful' in the name I hope its a colourful one.

### CODE REVIEW

**Comment by tomakita** [comment]
I've just checked out the code and tested it out in the example application -- this is really awesome! Thanks for this addition, and thanks for cleaning things up with the ignore file and removing the bin and obj folders.  I'm going to merge this later today, and will also update the colorfulconsole.com website with an example or two at that time.

I've also created a NuGet icon for the project (visible in the readme), and have been experimenting with project.json files and building with dnx.  It seems pretty cool.  The only thing I'm stuck on is xproj -- I can't seem to find any documentation for it online, and don't really know how to get started using it.  Is there any documentation that you know of?  I do see the .xproj file in your Boilerplate.Web.Mvc project, and it is helpful, but it'd be cool to see documentation, just to get an idea of how it works.  

As long as I can get the xproj thing figured out, my plan is to commit the project.json and .xproj files, and then upload the new NuGet package by the end of the weekend.

Thanks again for the contributions!

**Comment by tomakita** [comment]
Hey Muhammad, sorry for all the questions, but in addition to my question about .xproj files, I had one more question.  This is the first time anyone has contributed to a project of mine, so I'm not sure how to credit people for their work.  Should I mention your name on the colorfulconsole.com site?  Or is there another way that you'd prefer?  Pretty much any way is fine with me -- just let me know what be best.

**Comment by RehanSaeed** [comment]
Docs can be found [here](https://github.com/aspnet/Home/wiki/Project.json-file). As far as attribution is concerned. I need to do a better job of that too, so I'm not sure.

**Comment by tomakita** [comment]
Ok, your changes have been merged.  Thanks again for making this contribution!  I'm having trouble including the default "Small Slant.flf" font in a NuGet package, though.  Any ideas as to how I might do that?

**Comment by RehanSaeed** [comment]
Looks cool. You shouldn't need to do anything in a csproj, just set the file properties to be a resource. In xprok, there is a special section for assembly resources in project.json.

**Comment by tomakita** [comment]
Good to know.  I realized over the weekend that I didn't have ASP.NET 5.0 installed, which meant certain project types (such as "Class Library Package", which uses xproj instead of csproj) weren't available to me in Visual Studio.  This addresses a lot of my confusion with xproj, and I'm going to spend some time trying to make the switch from csproj to xproj when I have some time.  Thanks again for the advice!

**Pull request merged**
