### PR TITLE
Upgraded to RC2 and Added Provisional Support for Netstandard 1.3

### PR DESCRIPTION
**Pull request by RehanSaeed**
The support for netstandard 1.5 is commented out in project.json. To complete it the following needs to be resolved:

1. ExtensionMethods.Normalize needs to be changed so that it does not return a dynamic type.
2. I added a System.Drawing.Color type which is only compiled for `#if NETSTANDARD1_5`. There is a known colour table which needs to be filled in or known colours can be removed altogether. The choice is yours.

I have added TODO comments for both items so you can find them easily.

### CODE REVIEW

**Comment by RehanSaeed** [comment]
Other things to note and do:

1. netstandard1.5 does contain `System.Drawing.Primitives` but this does not contain the `Color` class. I have read somewhere that a cross platform version of `System.Drawing` is coming eventually but when is unknown.
2. I forgot to mention that obviously the ColorMapper class will not work on other platforms like Linux and Mac. The correct approach would be to work out the platform and make the OS calls to change the console colours.

A temporary workaround might involve using the current ColorMapper on Windows and switching it to a different one which just picks the nearest looking `ConsoleColor` to the `Color` you've asked for.

**Comment by tomakita** [comment]
Hey Muhammad,

Thanks for this update!  I don't have much spare time to work on this at the moment, so I've added you as a collaborator, which (I think) should allow you to merge this PR if you like.  Also, feel free to add your name to the "owners" array in the project.json files.  I'm happy to upload a new version of the NuGet package to the website, just let me know if that needs to be done.

Thanks again for this PR, and apologies for not being more helpful.

-Tom

**Comment by RehanSaeed** [comment]
Well, I haven't changed/added any functionality. Just upgraded the xproj project to RC2 and then tried and failed to support `netstandard1.3` so I commented that out in the `project.json` for the reasons I outlined above.

It can be merged but there is more work to do to add proper `netstandard1.3` support which I also will struggle to find time for. It's a start though...

**Comment by tomakita** [comment]
Still, the upgrade is appreciated.  Thanks for the PR!

**Pull request merged**
