### PR TITLE
Bunch of code improvements

### PR DESCRIPTION
**Pull request by MCCshreyas**
1. Removed unwanted code. 
2. Removed redundant else.
3. Converted code to expression body for better understanding.
4. Removed unused variable.
5. Simplified if block code.
6. Removed redundant class constructor.
7. Removed unused using directives.
8. Removed one redundant `String.Format` call in `ConsoleAccessException `class.
9. Added LINQ expression query instead of `foreach `loop in `ExtensionMethods` class. 
10. Used new object initializer way to initialize object.
11. Added new local functions to code instead of `Func<>` delegate.
12. Removed redundant this keyword.

### CODE REVIEW

**Comment by RehanSaeed** [comment]
C# 7.1 for the win!!!

I had a quick scan and it LGTM. @tomakita can confirm.

**Comment by tomakita** [comment]
@MCCshreyas Thanks for this great contribution!  I've looked through this PR, and have cloned your branch on my machine for some testing.  Everything looks great, with one small exception: I'm not quite able to understand the changes to the `ColorExtensions` (src/Colorful.Console/ColorExtensions.cs) class.  Can you walk me through the changes to this class?

@RehanSaeed Thanks for looking through these changes Muhammad!

**Comment by MCCshreyas** [comment]
The `Math.Abs(sum)` will round off the value of sum variable.
It is recommended that you should round off the double value before comparing it to float which is 0.0 in our case. That's why that change has been made. Not important one by the way, you can discard it.

**Comment by tomakita** [comment]
That's a good catch -- we should be checking for equality in a more robust way.  I might be wrong, but I'm not sure if comparing [Math.Abs](https://msdn.microsoft.com/en-us/library/f2yzeea2(v=vs.110).aspx) of the `sum` to zero will do this, though, because an absolute value can't be less than zero.  Instead, we can compare the `sum` to a value that is small enough that we can regard it as being equivalent to zero ( for the purposes of our problem, anyway).  Let's call this value `epsilon`.  If the `sum` is smaller than `epsilon`, then we can regard the `sum` itself as zero.  Also, we can avoid taking the absolute value of `sum`, because we know that it must be positive (it is the sum of 3 squares, and a value squared must always be positive).  So what if, instead of this:

```
if (Math.Abs(sum) < 0.0)
{
    return consoleColor;
}
```

We did this:

```
double epsilon = 0.001;
if (sum < epsilon)
{
    return consoleColor;
}
```

What do you think of this approach?

**Comment by MCCshreyas** [comment]
Yes. It is correct.

**Comment by MCCshreyas** [comment]
My pleasure. : ) 
Have a great day ahead.

**Pull request merged**
