### PR TITLE
README tweaks

### PR DESCRIPTION
**Pull request by drewnoakes**
Looks like a nice lib. Noticed a few small things in the README as I read through.

- Specify language in README code blocks. By adding `c#` to the code blocks, GitHub will show syntax highlighting.
- Fix Git clone command line capitalisation
- Escape some code bits

### CODE REVIEW

**Comment by tomakita** [comment]
Thanks -- the readme does look better now!

By the way, I'm a huge fan of your online FIX decoder: https://drewnoakes.com/fix-decoder/

The very first project that I open sourced was a low latency (I was proud of the performance at the time, anyway!) FIX decoder that I wrote in C#, and being able to use your decoder as a reference was a huge help both when getting familiar with FIX and when testing my implementation.  I recognized your name right away when I saw this pull request, and I'm honored that you would contribute to this project!!

**Comment by drewnoakes** [comment]
Seems it's a small world after all. Glad you found the decoder useful. It was a fun project to put together.

I hope to use Colorful.Console for some stuff I'm going to revamp soon, so thanks very much for making it available.

I found this while searching around for FIGlet fonts on .NET. The implementation at https://github.com/auriou/FIGlet doesn't fit glyphs, and doesn't implement the so-called "smushing" rules, so tends to make the output much wider than the font designers intended. I've been toying with some code that gives more control over rendering. If I get it to a point I'm happy with and up on NuGet, I'll let you know.

Also it looks like "extension everything" might be making it into C# 8, so when that day comes it might be possible to add your methods directly onto `System.Console`.

**Comment by tomakita** [comment]
Cool, I'd be interested to see how the FIGlet work goes!

It would be a dream to be able to extend `System.Console`, so if that feature does end up making it into C# 8, I would definitely take advantage of it.

**Comment by drewnoakes** [comment]
Pushed a first version of the project.

https://github.com/drewnoakes/figgle

It contains a bunch of fonts, so you could take it as a single dependency. Would be interested to get your feedback.

**Comment by tomakita** [comment]
This is very cool.  I like the ease of being able to reference fonts as static members of the `FiggleFonts` class -- that is a very cool feature.  Also, the smushing looks awesome.  After spending some time looking at the commit that implemented smushing, I get the feeling that this must have been tricky to implement.

Programming legend @RehanSaeed implemented the Colorful.Console FIGlet functionality.  Muhammad, if you get a chance, you may be interested in the project Drew linked to in his last post -- it's pretty sweet.

**Comment by RehanSaeed** [comment]
@drewnoakes Extension everything in C# 8 looks interesting indeed!

@tomakita Not that legendary I'm afraid. I'm struggling to find time to do basic open source at the moment so I've not had the chance to look in detail but my thoughts:

Embedding the fonts in an embedded zip file is a solid idea. When I looked into smushing, it was a difficult problem to solve as bringing two characters together means merging the characters (each individual character printed on screen and not the figlet character) into one and possibly changing their position too. I'd be interested the approach that was taken.

**Comment by drewnoakes** [comment]
@RehanSaeed the smushing logic is here:

https://github.com/drewnoakes/figgle/blob/master/Figgle/FiggleFont.cs#L231-L299

The embedded ZIP does increase the DLL size a bit though. If you knew you only wanted one font, it might be worth bundling it yourself. I could make a different NuGet package that didn't include any fonts. Will see if anyone complains, or even uses it for that matter! Mostly it was just a bit of fun one weekend.

**Comment by RehanSaeed** [comment]
Looks cool.

I think the approach we are currently using is to embed a single font and provide users the ability to add others themselves (we should make this easy using some documentation). Users will almost always only use one or two fonts. If you are worried about size, then that might be the way to go to avoid a bloated DLL.

It's up to @tomakita if he wants to take a dependency, it's only a handful of classes, I'd be inclined to include it in the box. Would also be a breaking change to change the API, unless you can make the API surface the same. Would be nice to include your nice features, nice work!

**Comment by tomakita** [comment]
Re: font bundling, I can think of two possibilities:

1. As you guys have said, allow the user to specify the fonts they want to use.  I'm sure we could come up with a cool way of doing this that wouldn't break the nice `FiggleFonts.[FontName]` syntax.  This wouldn't be too hard to implement, but would require that the user do some work to configure Figgle to use the font(s) they need.

2. Include all of the fonts, but in a compressed format.  We could use Roslyn to determine, at compile time, which fonts are being used (by looking at which members of the `FiggleFonts` class have been accessed).  We could then decompress only those fonts that are being used.  This way, users wouldn't need to know about font loading at all, but I actually don't know how feasible this would be, and it would also create a dependency on .NET 4.6 (for Roslyn), which probably isn't ideal.

It seems like #1 might be the better choice, but maybe there are other options that I'm missing?

**Comment by drewnoakes** [comment]
In Figgle the fonts are already stored in compressed format. It adds about 400kB to the DLL.

Up to you whether you'd like to take a dependency on the lib or not. I think I will include a 'lite' version of the package at some point that includes only a few common fonts. It's not high on my priority list right now though.

**Pull request merged**
